apiVersion: v1
kind: Namespace
metadata:
  name: hackajob-challenge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: hackajob-challenge
spec:
  selector:
    matchLabels:
      app: MyApp
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
      - name: nginx
        image: nginx:stable
---
apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: hackajob-challenge
spec:
  selector:
    app: MyApp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
